export const patient = [
    {
        _id: '13320',
        gender: 'm',
        name: 'julie',
        surname: 'jean',
        address: '35 rue du général leclerc',
        city: 'issy',
        zipcode: '92130',
        email: 'jean.cule@gmail.com',
        phone: '0612345678',
        doctor: 'dr Ibert',
        allergy: 'nan',
        vaccins: 'nan',
        notes: 'ras',
        secu: '123456422',
    },
    {
        _id: '13320',
        gender: 'm',
        name: 'neymar',
        surname: 'jean',
        address: '35 rue du général leclerc',
        city: 'issy',
        zipcode: '92130',
        email: 'jean.cule@gmail.com',
        phone: '0612345678',
        doctor: 'dr Ibert',
        allergy: 'nan',
        vaccins: 'nan',
        notes: 'ras',
        secu: '1234564789',
    },
    {
        _id: '13321',
        gender: 'f',
        name: 'julie',
        surname: 'lemoine',
        address: '35 rue du général leclerc',
        city: 'paris',
        zipcode: '75008',
        email: 'julie@gmail.com',
        phone: '0612345678',
        doctor: 'dr savoiris',
        allergy: 'gluten',
        vaccins: 'nan',
        notes: 'ras',
        secu: '1234564786',
    },
];


export const employees = [
    {
        _id: '13324',
        name: 'Thomas',
        surname: 'Good',
        gender: 'M',
        birthday: '08/12/1990',
        code: 133,
        status: 2,
        password: 'pass',
    },
    {
        _id: '13323',
        name: 'julien',
        surname: 'joveniaux',
        gender: 'M',
        birthday: '27/07/1993',
        code: 134,
        status: 1,
        password: 'pass',
    },
];
